/// @file codegen/Abi.hpp
/// @brief Typed, cached access to the runtime ABI surface.
///
/// ─── What This File Is ────────────────────────────────────────────────────
/// The codegen-side view of `runtime-abi/functions.def`. Given a
/// `RuntimeFn` enumerator (one per `__lucid_*` symbol), `Abi` produces the
/// LLVM declaration in the current module if it doesn't exist yet, builds
/// the matching `llvm::FunctionType`, and emits a call through a caller-
/// supplied `IRBuilder`.
///
/// The class has one method per row in `functions.def`. The methods are
/// generated by an X-macro expansion of the table, so the table stays the
/// single source of truth: adding a row to `functions.def` automatically
/// adds the corresponding method.
///
/// ─── What This File Is NOT ────────────────────────────────────────────────
/// It is NOT the runtime itself. The `extern "C"` implementations live in
/// `src/runtime/`. `Abi` never calls them directly — it only emits calls
/// in generated IR.
///
/// It is NOT the runtime-ABI contract. The layouts (`lucid.String`,
/// `lucid.Arena`, ...) come from `runtime-abi/lucid_abi.h`, and the
/// type-tag vocabulary from `runtime-abi/functions.def`. `Abi` reads them;
/// it does not define them.
///
/// It is NOT the emitter. It does not know about Lucid AST nodes, ownership
/// rules, or scopes. It only knows how to call one specific runtime
/// function with a set of already-lowered `llvm::Value*` arguments.
///
/// ─── Why a Class, Not Free Functions ──────────────────────────────────────
/// Each declared `llvm::Function*` must be cached per module: the first
/// `abi.Alloc(...)` in a module declares `__lucid_alloc`, and every later
/// call reuses the same `llvm::Function*`. That cache is state, and the
/// state belongs to a program. `Abi` is constructed once per
/// `ProgramState`, holds the cache, and is reached as `ctx.abi()`.
///
/// The cache is keyed on the `RuntimeFn` enumerator. Because codegen
/// produces one `llvm::Module` per program in the new design, one cache
/// serves one module, and the "which module did this symbol come from"
/// problem that the old `CodeGenContext::runtimeFunctions` map had is
/// structurally impossible.
///
/// ─── Why `ProgramState&`, Not `Module&` ───────────────────────────────────
/// `Abi` needs to record which runtime functions the program actually
/// uses, so the manifest can list them and the interpreter/AOT linker can
/// decide which runtime objects to link. The usage set lives on
/// `ProgramState`. Rather than hold separate references to the module and
/// the usage set, `Abi` holds one reference to the `ProgramState` and reads
/// both from it. It needs no `Types`: the runtime ABI passes structs by
/// pointer, so every runtime signature is built from scalars and `ptr`.
///
/// This also means `Abi` is a *component of* `ProgramState`, not an
/// independent object. That's the intended relationship: there is one
/// `Abi` per program, constructed by `ProgramState`, destroyed with it.

#pragma once

#include <llvm/ADT/ArrayRef.h>
#include <llvm/IR/Function.h>
#include <llvm/IR/IRBuilder.h>
#include <llvm/IR/LLVMContext.h>
#include <llvm/IR/Module.h>
#include <llvm/IR/Type.h>

#include <cstdint>
#include <string_view>
#include <type_traits>
#include <unordered_map>

namespace codegen {

// Forward declaration. `Abi.cpp` includes `Program.hpp` for the full
// definition; `Abi.hpp` only needs the name to hold a reference.
class ProgramState;

// ─────────────────────────────────────────────────────────────────────────────
// RuntimeFn — one enumerator per runtime ABI symbol
// ─────────────────────────────────────────────────────────────────────────────
//
// Generated from `functions.def`. Each row in that table becomes one
// enumerator whose name is the row's first column. The enumerator is what
// `Abi`'s cache is keyed on and what codegen call sites pass to identify
// the runtime function they want.
//
// The enumerator names are the only thing generated here. The symbol
// string (the second column of the table) is not stored on the enumerator;
// it's looked up inside `Abi.cpp` when the declaration is first built.

#define LUCID_RT(EnumName, Symbol, Ret, Params) EnumName,
enum class RuntimeFn {
#include "runtime-abi/functions.def"
};
#undef LUCID_RT

// ─────────────────────────────────────────────────────────────────────────────
// Abi — typed, cached runtime call surface
// ─────────────────────────────────────────────────────────────────────────────

class Abi {
public:
    /// @brief Construct an `Abi` for one program.
    ///
    /// The reference must outlive the `Abi`. In practice `Abi` is a member
    /// of `ProgramState`, so this is guaranteed by construction: the
    /// `ProgramState` is fully constructed before any of its members are
    /// used.
    explicit Abi(ProgramState& program);

    Abi(const Abi&) = delete;
    Abi& operator=(const Abi&) = delete;
    Abi(Abi&&) = delete;
    Abi& operator=(Abi&&) = delete;

    // ─── Method Definitions ───────────────────────────────────────────────
    //
    // Generated from `functions.def`. Each row produces one member function
    // template named after the row's enumerator:
    //
    //     abi.StrSlice(builder, out, s, from, to);
    //     abi.LeakReport(builder);
    //
    // The template is variadic on purpose. The table is the only place the
    // parameter list is written down; C++ does not re-count it. That removes
    // the preprocessor arity dispatch (and its cap and its empty-tuple
    // trap). Instead `emitCall` checks, in debug builds, that the argument
    // count and every argument's LLVM type match the row.
    //
    // Returns the call's result, or `nullptr` for `Void` functions. Not
    // `const`: the first call for a given function mutates the cache.

#define LUCID_RT(EnumName, Symbol, Ret, Params)                               \
    template <typename... Vs>                                                 \
    llvm::Value* EnumName(llvm::IRBuilder<>& builder, Vs... args) {           \
        static_assert((std::is_convertible_v<Vs, llvm::Value*> && ...),       \
                      #EnumName ": every argument must be an llvm::Value*");  \
        return emitCall(RuntimeFn::EnumName, builder,                         \
                        {static_cast<llvm::Value*>(args)...});                \
    }

#include "runtime-abi/functions.def"
#undef LUCID_RT

    // ─── Raw Access ───────────────────────────────────────────────────────
    //
    // The `llvm::Function*` for a runtime function, declaring it if needed
    // and recording the usage. Most codegen call sites go through the
    // typed methods above, but a few places (like `emitCallableCall` when
    // the callee is a runtime function passed as a value) need the raw
    // pointer.
    //
    // `fn` must be a valid enumerator. The symbol name and signature are
    // looked up from `functions.def` and the layout headers.
    llvm::Function* declareOrGet(RuntimeFn fn);

    // This is the single place the `RuntimeFn` enumerator is mapped back to
    // its `__lucid_*` symbol string, so the manifest cannot disagree with
    // the actual declaration.
    std::string_view symbolName(RuntimeFn fn) const;

private:
    // ─── Internals ────────────────────────────────────────────────────────

    /// @brief Shared body of every generated method: declare, check, call.
    ///
    /// Asserts (debug builds) that `args` matches the row's parameter count
    /// and LLVM types, so passing an `i64` where the table says `Str` fails
    /// at the call site instead of producing bad IR.
    llvm::Value* emitCall(RuntimeFn fn,
                          llvm::IRBuilder<>& builder,
                          llvm::ArrayRef<llvm::Value*> args);

    /// @brief Build the `llvm::FunctionType` for a runtime function.
    ///
    /// Reads the row from `functions.def` and expands the tags into LLVM
    /// types. Called once per runtime function, at declaration time. Any
    /// attributes the tags imply (`zeroext` for `I1`) are applied by
    /// `declareOrGet`, because they live on the function, not the type.
    llvm::FunctionType* buildFunctionType(RuntimeFn fn);

    // ─── State ────────────────────────────────────────────────────────────

    ProgramState& program_;

    /// Cache of declared runtime functions. Keyed on the enumerator, one
    /// entry per `__lucid_*` symbol that has been used. `buildFunctionType`
    /// only runs on a miss here, so it needs no cache of its own.
    std::unordered_map<RuntimeFn, llvm::Function*> functionCache;
};

} // namespace codegen