/// @file codegen/Abi.hpp
/// @brief Typed, cached access to the runtime ABI surface.
///
/// ─── What This File Is ────────────────────────────────────────────────────
/// The codegen-side view of `runtime-abi/functions.def`. Given a
/// `RuntimeFn` enumerator (one per `__lucid_*` symbol), `Abi` produces the
/// LLVM declaration in the current module if it doesn't exist yet, builds
/// the matching `llvm::FunctionType`, and emits a call through a caller-
/// supplied `IRBuilder`.
///
/// The class has one method per row in `functions.def`. The methods are
/// generated by an X-macro expansion of the table, so the table stays the
/// single source of truth: adding a row to `functions.def` automatically
/// adds the corresponding method.
///
/// ─── What This File Is NOT ────────────────────────────────────────────────
/// It is NOT the runtime itself. The `extern "C"` implementations live in
/// `src/runtime/`. `Abi` never calls them directly — it only emits calls
/// in generated IR.
///
/// It is NOT the runtime-ABI contract. The layouts (`lucid.String`,
/// `lucid.Arena`, ...) and the type-tag vocabulary come from
/// `runtime-abi/lucid_abi.h`. `Abi` reads them; it does not define them.
///
/// It is NOT the emitter. It does not know about Lucid AST nodes, ownership
/// rules, or scopes. It only knows how to call one specific runtime
/// function with a set of already-lowered `llvm::Value*` arguments.
///
/// ─── Why a Class, Not Free Functions ──────────────────────────────────────
/// Each declared `llvm::Function*` must be cached per module: the first
/// `abi.alloc(...)` in a module declares `__lucid_alloc`, and every later
/// call reuses the same `llvm::Function*`. That cache is state, and the
/// state belongs to a program. `Abi` is constructed once per
/// `ProgramState`, holds the cache, and is reached as `ctx.abi()`.
///
/// The cache is keyed on the `RuntimeFn` enumerator. Because codegen
/// produces one `llvm::Module` per program in the new design, one cache
/// serves one module, and the "which module did this symbol come from"
/// problem that the old `CodeGenContext::runtimeFunctions` map had is
/// structurally impossible.
///
/// ─── Why `ProgramState&`, Not `Module&` + `Types&` ────────────────────────
/// `Abi` needs to record which runtime functions the program actually
/// uses, so the manifest can list them and the interpreter/AOT linker can
/// decide which runtime objects to link. The usage set lives on
/// `ProgramState`. Rather than hold separate references to the module,
/// the types, and the usage set, `Abi` holds one reference to the
/// `ProgramState` and reads all three from it.
///
/// This also means `Abi` is a *component of* `ProgramState`, not an
/// independent object. That's the intended relationship: there is one
/// `Abi` per program, constructed by `ProgramState`, destroyed with it.

#pragma once

#include "Types.hpp"

#include <llvm/IR/Function.h>
#include <llvm/IR/IRBuilder.h>
#include <llvm/IR/LLVMContext.h>
#include <llvm/IR/Module.h>
#include <llvm/IR/Type.h>

#include <cstdint>
#include <string_view>
#include <unordered_map>

namespace codegen {

// Forward declaration. `Abi.cpp` includes `Program.hpp` for the full
// definition; `Abi.hpp` only needs the name to hold a reference.
class ProgramState;

// ─────────────────────────────────────────────────────────────────────────────
// RuntimeFn — one enumerator per runtime ABI symbol
// ─────────────────────────────────────────────────────────────────────────────
//
// Generated from `functions.def`. Each row in that table becomes one
// enumerator whose name is the row's first column. The enumerator is what
// `Abi`'s cache is keyed on and what codegen call sites pass to identify
// the runtime function they want.
//
// The enumerator names are the only thing generated here. The symbol
// string (the second column of the table) is not stored on the enumerator;
// it's looked up inside `Abi.cpp` when the declaration is first built.

#define LUCID_RT(EnumName, Symbol, Ret, Params) EnumName,
enum class RuntimeFn {
#include "runtime-abi/functions.def"
};
#undef LUCID_RT

// ─────────────────────────────────────────────────────────────────────────────
// Arity helpers for the X-macro method-signature expansion
// ─────────────────────────────────────────────────────────────────────────────
//
// Every runtime function takes zero or more `llvm::Value*` arguments. The
// types differ only in the `llvm::FunctionType`, which is built inside the
// method body. So the C++ method signature is uniform in shape: all
// parameters are `llvm::Value*`, and the arity is all that varies.
//
// These macros expand a parenthesized tuple of tags — `(I64, Ptr)` — into
// a comma-separated list of `llvm::Value*` parameters with named
// parameters `_a0`, `_a1`, ... The tag values themselves (`I64`, `Ptr`,
// etc.) are not used in the signature — they're used inside the body to
// build the `llvm::FunctionType`. The method treats them as opaque.
//
// Arity is capped at 3 because no row in `functions.def` has more than
// 3 parameters. Adding a row with 4 would require adding
// `LUCID_RT_PARAMS_4` below and extending the dispatch macro.

#define LUCID_RT_PARAMS_0()
#define LUCID_RT_PARAMS_1(A)          llvm::Value* _a0
#define LUCID_RT_PARAMS_2(A, B)       llvm::Value* _a0, llvm::Value* _a1
#define LUCID_RT_PARAMS_3(A, B, C)    llvm::Value* _a0, llvm::Value* _a1, \
                                      llvm::Value* _a2

// Dispatch on the number of arguments in the tuple.
//
// `LUCID_RT_GET_MACRO` picks the Nth-name macro from a list based on how
// many args follow it. With 3 named prefixes, the last argument is always
// the one that wins. So `LUCID_RT_GET_MACRO(a, b, c, _3, _2, _1, _0)`
// expands to `_3`. The trick is that the tuple's commas are what make
// the counting work.
#define LUCID_RT_GET_MACRO(_1, _2, _3, NAME, ...) NAME

// The empty tuple `()` matches `LUCID_RT_GET_MACRO(_1, _2, _3, ...)`
// with `_1 = `, `_2 = `, `_3 = ` — the trailing arguments vanish. That
// is, `LUCID_RT_GET_MACRO()` expands to `_3` (the last of the fixed
// names). This is a known quirk of the pattern; the arity-0 dispatch
// works because all three slots are empty.
#define LUCID_RT_APPLY_PARAMS_0() LUCID_RT_PARAMS_0()
#define LUCID_RT_APPLY_PARAMS_1(A) LUCID_RT_PARAMS_1(A)
#define LUCID_RT_APPLY_PARAMS_2(A, B) LUCID_RT_PARAMS_2(A, B)
#define LUCID_RT_APPLY_PARAMS_3(A, B, C) LUCID_RT_PARAMS_3(A, B, C)

// `LUCID_RT_ARGS` takes the parenthesized params tuple and produces the
// C++ parameter list.
//
// Usage: `LUCID_RT_ARGS((I64, Ptr))` → `llvm::Value* _a0, llvm::Value* _a1`
//
// This is the mechanism that keeps the method signature in sync with the
// row's arity without hand-writing it.
#define LUCID_RT_ARGS(Params) \
    LUCID_RT_GET_MACRO Params (LUCID_RT_APPLY_PARAMS_3, \
                                LUCID_RT_APPLY_PARAMS_2, \
                                LUCID_RT_APPLY_PARAMS_1, \
                                LUCID_RT_APPLY_PARAMS_0) Params

// ─────────────────────────────────────────────────────────────────────────────
// Abi — typed, cached runtime call surface
// ─────────────────────────────────────────────────────────────────────────────

class Abi {
public:
    /// @brief Construct an `Abi` for one program.
    ///
    /// The reference must outlive the `Abi`. In practice `Abi` is a member
    /// of `ProgramState`, so this is guaranteed by construction: the
    /// `ProgramState` is fully constructed before any of its members are
    /// used.
    explicit Abi(ProgramState& program);

    Abi(const Abi&) = delete;
    Abi& operator=(const Abi&) = delete;
    Abi(Abi&&) = delete;
    Abi& operator=(Abi&&) = delete;

    // ─── Method Declarations ──────────────────────────────────────────────
    //
    // Generated from `functions.def`. Each row produces one method whose
    // name is the row's enumerator and whose C++ signature is
    // `llvm::Value* method(llvm::IRBuilder<>&, llvm::Value*, ...)` — one
    // argument per tuple element, all typed as `llvm::Value*`.
    //
    // Inside the generated method (see Abi.cpp):
    //   1. The runtime function is declared if not already declared, and
    //      the enumerator is recorded in `program_.usedRuntimeFns()`.
    //   2. The call is emitted through the caller-supplied `IRBuilder`.
    //
    // The methods are not `const` because they mutate the cache on first
    // call. Callers should treat the returned `llvm::Value*` as the call's
    // result value.

#define LUCID_RT(EnumName, Symbol, Ret, Params) \
    llvm::Value* EnumName(llvm::IRBuilder<>& builder, \
                          LUCID_RT_ARGS(Params));

#include "runtime-abi/functions.def"
#undef LUCID_RT

    // ─── Raw Access ───────────────────────────────────────────────────────
    //
    // The `llvm::Function*` for a runtime function, declaring it if needed
    // and recording the usage. Most codegen call sites go through the
    // typed methods above, but a few places (like `emitCallableCall` when
    // the callee is a runtime function passed as a value) need the raw
    // pointer.
    //
    // `fn` must be a valid enumerator. The symbol name and signature are
    // looked up from `functions.def` and the layout headers.
    llvm::Function* declareOrGet(RuntimeFn fn);

    // ─── Convenience ──────────────────────────────────────────────────────

    /// @brief `__lucid_panic` is marked `noreturn` in the generated IR.
    ///
    /// The panic runtime function never returns. Codegen needs to know this
    /// so it can omit the fall-through block after a panic call.
    llvm::Function* panicFn();

    /// @brief `__lucid_shutdown` is emitted at the end of `main`.
    llvm::Function* shutdownFn();

private:
    // ─── Internals ────────────────────────────────────────────────────────

    /// @brief Build the `llvm::FunctionType` for a runtime function.
    ///
    /// Reads the row from `functions.def` and expands the tags into LLVM
    /// types. Called once per runtime function, at declaration time.
    llvm::FunctionType* buildFunctionType(RuntimeFn fn);

    /// @brief Look up the symbol name for a runtime function.
    std::string_view symbolName(RuntimeFn fn) const;

    // ─── State ────────────────────────────────────────────────────────────

    ProgramState& program_;

    /// Cache of declared runtime functions. Keyed on the enumerator, one
    /// entry per `__lucid_*` symbol that has been used.
    std::unordered_map<RuntimeFn, llvm::Function*> functionCache;

    /// Cache of built `llvm::FunctionType`s. Separate from the function
    /// cache because a function can be looked up without being called
    /// (via `declareOrGet`), and because building a `FunctionType` and
    /// creating a `Function` are logically distinct operations.
    std::unordered_map<RuntimeFn, llvm::FunctionType*> typeCache;
};

} // namespace codegen